language: python
python:
  - "3.6" # Supported until at least 2021-12-23 upstream, never ran by us.
  - "3.7" # Our instance, supported until at least 2023-06-27 upstream.
  - "3.8" # previous release - support until 2024-10-14
  - "3.8-dev"  # 3.8 development branch - remove after 2021-03-22
  - "3.9" # latest- support until 2025-10-05
  - "3.9-dev" # 3.9 development branch - remove by 2022
os: linux
dist: focal
group: edge
arch: arm64-graviton2
virt: lxd
cache: pip

install:
    - pip install -r test-requirements.txt
before_script:
    - python --version
    - sopel --version
    - pip show MirahezeBot-Plugins

script:
    - flake8 MirahezeBots/plugins --max-line-length 265 --exclude=__init__.py
    - flake8 tests --max-line-length 265
    - flake8 MirahezeBots/utils --max-line-length 265 --exclude=__init__.py
    - pytest tests/test_general.py
    - pytest tests/test_rss.py
    - pytest tests/test_json.py
    - pip-missing-reqs --ignore-file=setup.py --ignore-module=pytest --ignore-module=MirahezeBots.* .
    - pip-extra-reqs --ignore-requirement=sopel-plugins.adminlist --ignore-requirement=sopel-plugins.channelmgnt --ignore-requirement=sopel-plugins.pingpong --ignore-requirement=sopel-plugins.joinall .
    - pip check

after_script:
    - pip freeze
    - pipdeptree
    
notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze-bots"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
